# Generated by Django 4.2.11 on 2024-05-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='important',
        ),
    ]
