# Generated by Django 4.2.11 on 2024-05-07 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_todo_completed_alter_todo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='updated',
        ),
    ]
