# Generated by Django 4.2.11 on 2024-05-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_todo_description_remove_todo_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='name',
        ),
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.CharField(default='', max_length=80, null=True),
        ),
    ]
